@Ruig.Api_HostAddress = http://localhost:5129
@Ruig.Api_HttpsAddress = https://localhost:7287

GET {{Ruig.Api_HttpsAddress}}/auth/strava/start
Accept: application/json

###

# After approving Strava OAuth in the browser, Strava redirects here with code/state.
# Paste values from the browser URL to manually exercise the callback.
GET {{Ruig.Api_HttpsAddress}}/auth/strava/callback?code={{strava_code}}&state={{strava_state}}
Accept: application/json

###

GET {{Ruig.Api_HostAddress}}/webhooks/strava?hub.mode=subscribe&hub.verify_token=ruig-dev-webhook-token&hub.challenge=test-challenge
Accept: application/json

###

POST {{Ruig.Api_HostAddress}}/webhooks/strava
Content-Type: application/json

{
  "object_type": "activity",
  "object_id": 987,
  "aspect_type": "create",
  "owner_id": 123,
  "subscription_id": 456,
  "event_time": 1800000000,
  "updates": {}
}

###
